name = "BlockTopia 3"
author = "Pichon_8"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80cd1a7c949baaac031f16b50b5668cb175d49f8b36e6187c61ddfe8bc8938b4"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
